import { Resource, ResourceCategory } from '@/types/resources'

export const RESOURCE_TYPES = [
  { value: 'article', label: 'Article', icon: '📄', color: 'blue' },
  { value: 'video', label: 'Video', icon: '🎥', color: 'red' },
  { value: 'audio', label: 'Audio', icon: '🎵', color: 'purple' },
  { value: 'podcast', label: 'Podcast', icon: '🎙️', color: 'orange' },
  { value: 'book', label: 'Book', icon: '📚', color: 'green' },
  { value: 'guide', label: 'Guide', icon: '📖', color: 'indigo' },
  { value: 'worksheet', label: 'Worksheet', icon: '📝', color: 'pink' },
  { value: 'external', label: 'External Link', icon: '🔗', color: 'gray' },
]

export const RESOURCE_STATUS = [
  { value: 'draft', label: 'Draft', color: 'gray' },
  { value: 'published', label: 'Published', color: 'green' },
  { value: 'archived', label: 'Archived', color: 'red' },
]

export const RESOURCE_CATEGORIES: ResourceCategory[] = [
  {
    id: '1',
    name: 'Anxiety & Stress',
    slug: 'anxiety-stress',
    description: 'Resources for managing anxiety and stress through faith-based approaches',
    icon: '😰',
    color: 'blue',
    resourceCount: 24,
    createdAt: '2025-01-01',
  },
  {
    id: '2',
    name: 'Depression',
    slug: 'depression',
    description: 'Support and resources for dealing with depression',
    icon: '😔',
    color: 'indigo',
    resourceCount: 18,
    createdAt: '2025-01-01',
  },
  {
    id: '3',
    name: 'Faith & Spirituality',
    slug: 'faith-spirituality',
    description: 'Faith-based mental health resources and devotionals',
    icon: '🙏',
    color: 'purple',
    resourceCount: 32,
    createdAt: '2025-01-01',
  },
  {
    id: '4',
    name: 'Relationships',
    slug: 'relationships',
    description: 'Resources for healthy relationships and communication',
    icon: '💑',
    color: 'pink',
    resourceCount: 15,
    createdAt: '2025-01-01',
  },
  {
    id: '5',
    name: 'Trauma & PTSD',
    slug: 'trauma-ptsd',
    description: 'Healing from trauma and PTSD',
    icon: '🕊️',
    color: 'red',
    resourceCount: 12,
    createdAt: '2025-01-01',
  },
  {
    id: '6',
    name: 'Parenting',
    slug: 'parenting',
    description: 'Resources for parents and family wellness',
    icon: '👪',
    color: 'green',
    resourceCount: 20,
    createdAt: '2025-01-01',
  },
  {
    id: '7',
    name: 'Grief & Loss',
    slug: 'grief-loss',
    description: 'Coping with grief and finding hope',
    icon: '🕯️',
    color: 'gray',
    resourceCount: 10,
    createdAt: '2025-01-01',
  },
  {
    id: '8',
    name: 'Self-Care',
    slug: 'self-care',
    description: 'Practices and resources for self-care',
    icon: '🧘',
    color: 'teal',
    resourceCount: 28,
    createdAt: '2025-01-01',
  },
]

export const MOCK_RESOURCES: Resource[] = [
  {
    id: '1',
    title: 'Understanding Anxiety: A Faith-Based Approach',
    description: 'Learn how to manage anxiety through faith and practical techniques. This comprehensive guide combines clinical insights with spiritual wisdom.',
    content: 'Full content here...',
    type: 'book',
    category: 'anxiety-stress',
    tags: ['anxiety', 'faith', 'prayer', 'mental health'],
    author: 'Dr. Sarah Johnson',
    authorId: 'auth1',
    status: 'published',
    featured: true,
    views: 1243,
    likes: 89,
    shares: 34,
    thumbnail: '/thumbnails/anxiety-book.jpg',
    coverImage: '/covers/anxiety-cover.jpg',
    pages: 248,
    publisher: 'HopePath Publishing',
    isbn: '978-1-23456-789-0',
    publicationDate: '2024-01-15',
    duration: 480, // reading time in minutes
    createdAt: '2024-01-10',
    publishedAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Daily Devotionals for Mental Wellness',
    description: '30 days of devotionals to support your mental health journey. Each day includes scripture, reflection questions, and practical exercises.',
    content: 'Full content here...',
    type: 'book',
    category: 'faith-spirituality',
    tags: ['devotional', 'daily', 'faith', 'wellness'],
    author: 'Pastor Michael Brown',
    authorId: 'auth2',
    status: 'published',
    featured: true,
    views: 3456,
    likes: 234,
    shares: 156,
    thumbnail: '/thumbnails/devotionals.jpg',
    coverImage: '/covers/devotionals-cover.jpg',
    pages: 180,
    publisher: 'Faith & Wellness Press',
    isbn: '978-1-23456-788-3',
    publicationDate: '2024-02-01',
    duration: 360,
    createdAt: '2024-01-20',
    publishedAt: '2024-02-01',
    updatedAt: '2024-02-01',
  },
  {
    id: '3',
    title: 'Meditation for Stress Relief',
    description: 'Guided meditation audio for stress relief. Includes 10 guided sessions ranging from 5 to 20 minutes.',
    content: 'Audio content...',
    type: 'audio',
    category: 'anxiety-stress',
    tags: ['meditation', 'stress', 'mindfulness', 'guided'],
    author: 'Dr. Sarah Johnson',
    authorId: 'auth1',
    status: 'published',
    featured: false,
    views: 876,
    likes: 67,
    shares: 23,
    thumbnail: '/thumbnails/meditation.jpg',
    fileUrl: '/audio/meditation.mp3',
    duration: 15, // minutes per session
    createdAt: '2024-02-05',
    publishedAt: '2024-02-06',
    updatedAt: '2024-02-06',
  },
  {
    id: '4',
    title: 'Faith & Mental Health Podcast: Season 1',
    description: 'A podcast series exploring the intersection of faith and mental health. Each episode features interviews with therapists, pastors, and individuals sharing their stories.',
    content: 'Podcast episodes...',
    type: 'podcast',
    category: 'faith-spirituality',
    tags: ['podcast', 'faith', 'mental health', 'interviews'],
    author: 'Dr. Emily White & Pastor Michael Brown',
    authorId: 'auth3',
    status: 'published',
    featured: true,
    views: 2341,
    likes: 178,
    shares: 89,
    thumbnail: '/thumbnails/podcast.jpg',
    fileUrl: '/podcast/season1/episode1.mp3',
    duration: 45, // minutes per episode
    metadata: {
      episodes: 12,
      season: 1,
    },
    createdAt: '2024-02-10',
    publishedAt: '2024-02-15',
    updatedAt: '2024-02-15',
  },
  {
    id: '5',
    title: 'Coping with Grief: A Christian Perspective',
    description: 'A video series on understanding grief and finding hope. Includes teaching sessions and real-life testimonies.',
    content: 'Video content...',
    type: 'video',
    category: 'grief-loss',
    tags: ['grief', 'loss', 'hope', 'video series'],
    author: 'Dr. Michael Chen',
    authorId: 'auth4',
    status: 'published',
    featured: false,
    views: 1542,
    likes: 98,
    shares: 45,
    thumbnail: '/thumbnails/grief-video.jpg',
    fileUrl: '/videos/grief-series/ep1.mp4',
    duration: 60,
    createdAt: '2024-02-18',
    publishedAt: '2024-02-20',
    updatedAt: '2024-02-20',
  },
  
]

export const RESOURCE_STATS: ResourceStats = {
  totalResources: MOCK_RESOURCES.length,
  publishedResources: MOCK_RESOURCES.filter(r => r.status === 'published').length,
  draftResources: MOCK_RESOURCES.filter(r => r.status === 'draft').length,
  archivedResources: MOCK_RESOURCES.filter(r => r.status === 'archived').length,
  totalViews: MOCK_RESOURCES.reduce((acc, r) => acc + r.views, 0),
  totalLikes: MOCK_RESOURCES.reduce((acc, r) => acc + r.likes, 0),
  totalShares: MOCK_RESOURCES.reduce((acc, r) => acc + r.shares, 0),
  averageRating: 4.7,
  popularCategories: [
    { category: 'Anxiety & Stress', count: 3, views: 2773 },
    { category: 'Faith & Spirituality', count: 3, views: 6680 },
    { category: 'Grief & Loss', count: 1, views: 1542 },
    { category: 'Parenting', count: 1, views: 0 },
    { category: 'Trauma & PTSD', count: 1, views: 2345 },
  ],
  recentUploads: MOCK_RESOURCES.slice(0, 5),
  topResources: MOCK_RESOURCES
    .sort((a, b) => b.views - a.views)
    .slice(0, 5)
    .map(r => ({ id: r.id, title: r.title, views: r.views, type: r.type })),
}