FROM python:3.12-slim-bookworm

WORKDIR /code

# Update system packages to latest
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/code
ENV PORT=7860

CMD gunicorn --bind :$PORT --workers 4 --threads 8 --timeout 0 app:app