FROM python:3.11

WORKDIR /app
COPY . .

RUN pip install fastapi uvicorn pymongo cryptography transformers torch accelerate

EXPOSE 7860

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"]
