import { User, UserStats } from '@/types/user'

export const USER_ROLES = [
  { value: 'user', label: 'User', color: 'blue' },
  { value: 'premium', label: 'Premium', color: 'purple' },
  { value: 'counselor', label: 'Counselor', color: 'green' },
  { value: 'admin', label: 'Admin', color: 'red' },
]

export const USER_STATUS = [
  { value: 'active', label: 'Active', color: 'green' },
  { value: 'inactive', label: 'Inactive', color: 'gray' },
  { value: 'suspended', label: 'Suspended', color: 'red' },
  { value: 'pending', label: 'Pending', color: 'yellow' },
]

export const MOCK_USERS: User[] = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    phone: '+1-876-555-0123',
    dateOfBirth: '1990-05-15',
    gender: 'male',
    status: 'active',
    role: 'user',
    emailVerified: true,
    phoneVerified: true,
    twoFactorEnabled: false,
    bio: 'Seeking support for anxiety and stress management.',
    occupation: 'Teacher',
    interests: ['Reading', 'Meditation', 'Running'],
    totalSessions: 12,
    totalResources: 24,
    totalReviews: 3,
    lastActive: '2025-03-10T14:30:00Z',
    joinedDate: '2025-01-15T10:00:00Z',
    preferences: {
      newsletter: true,
      notifications: true,
      language: 'en',
      theme: 'system',
    },
    emergencyContact: {
      name: 'Jane Doe',
      relationship: 'Spouse',
      phone: '+1-876-555-0124',
      email: 'jane.doe@example.com',
    },
    tags: ['anxiety', 'stress-management'],
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-03-10T14:30:00Z',
    lastLoginAt: '2025-03-10T14:30:00Z',
  },
  {
    id: '2',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    phone: '+1-876-555-0125',
    dateOfBirth: '1988-09-22',
    gender: 'female',
    status: 'active',
    role: 'premium',
    emailVerified: true,
    phoneVerified: true,
    twoFactorEnabled: true,
    bio: 'Working through relationship challenges and seeking personal growth.',
    occupation: 'Graphic Designer',
    interests: ['Art', 'Yoga', 'Journaling'],
    totalSessions: 24,
    totalResources: 45,
    totalReviews: 8,
    lastActive: '2025-03-11T09:15:00Z',
    joinedDate: '2025-01-10T09:00:00Z',
    preferences: {
      newsletter: true,
      notifications: true,
      language: 'en',
      theme: 'dark',
    },
    emergencyContact: {
      name: 'Tom Smith',
      relationship: 'Brother',
      phone: '+1-876-555-0126',
    },
    tags: ['relationships', 'personal-growth'],
    createdAt: '2025-01-10T09:00:00Z',
    updatedAt: '2025-03-11T09:15:00Z',
    lastLoginAt: '2025-03-11T09:15:00Z',
  },
  {
    id: '3',
    firstName: 'Robert',
    lastName: 'Johnson',
    email: 'robert.johnson@example.com',
    phone: '+1-876-555-0127',
    status: 'suspended',
    role: 'user',
    emailVerified: true,
    phoneVerified: false,
    twoFactorEnabled: false,
    totalSessions: 3,
    totalResources: 8,
    totalReviews: 0,
    lastActive: '2025-02-28T16:20:00Z',
    joinedDate: '2025-02-01T11:30:00Z',
    preferences: {
      newsletter: false,
      notifications: true,
      language: 'en',
      theme: 'light',
    },
    suspendedUntil: '2025-04-01T00:00:00Z',
    suspensionReason: 'Payment issue',
    createdAt: '2025-02-01T11:30:00Z',
    updatedAt: '2025-02-28T16:20:00Z',
  },
  {
    id: '4',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'maria.garcia@example.com',
    phone: '+1-876-555-0128',
    dateOfBirth: '1995-03-10',
    gender: 'female',
    status: 'inactive',
    role: 'user',
    emailVerified: true,
    phoneVerified: true,
    twoFactorEnabled: false,
    totalSessions: 0,
    totalResources: 5,
    totalReviews: 0,
    lastActive: '2025-02-15T10:45:00Z',
    joinedDate: '2025-02-10T14:20:00Z',
    preferences: {
      newsletter: true,
      notifications: true,
      language: 'es',
      theme: 'system',
    },
    createdAt: '2025-02-10T14:20:00Z',
    updatedAt: '2025-02-15T10:45:00Z',
  },
  {
    id: '5',
    firstName: 'David',
    lastName: 'Brown',
    email: 'david.brown@example.com',
    phone: '+1-876-555-0129',
    dateOfBirth: '1985-07-18',
    gender: 'male',
    status: 'pending',
    role: 'user',
    emailVerified: false,
    phoneVerified: false,
    twoFactorEnabled: false,
    totalSessions: 0,
    totalResources: 0,
    totalReviews: 0,
    lastActive: '2025-03-12T08:30:00Z',
    joinedDate: '2025-03-12T08:30:00Z',
    preferences: {
      newsletter: true,
      notifications: true,
      language: 'en',
      theme: 'system',
    },
    createdAt: '2025-03-12T08:30:00Z',
    updatedAt: '2025-03-12T08:30:00Z',
  },
]

export const MOCK_USER_STATS: UserStats = {
  totalUsers: MOCK_USERS.length,
  activeUsers: MOCK_USERS.filter(u => u.status === 'active').length,
  suspendedUsers: MOCK_USERS.filter(u => u.status === 'suspended').length,
  pendingUsers: MOCK_USERS.filter(u => u.status === 'pending').length,
  premiumUsers: MOCK_USERS.filter(u => u.role === 'premium').length,
  newUsersToday: 2,
  newUsersThisWeek: 8,
  newUsersThisMonth: 15,
  averageSessionsPerUser: 8.5,
  topUsers: [
    { id: '2', name: 'Jane Smith', sessions: 24 },
    { id: '1', name: 'John Doe', sessions: 12 },
    { id: '3', name: 'Robert Johnson', sessions: 3 },
  ],
}

export const MOCK_USER_ACTIVITY: UserActivity[] = [
  {
    id: 'act1',
    userId: '1',
    type: 'login',
    action: 'User logged in',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0...',
    timestamp: '2025-03-10T14:30:00Z',
  },
  {
    id: 'act2',
    userId: '1',
    type: 'session',
    action: 'Completed therapy session',
    details: 'Session with Dr. Sarah Johnson',
    timestamp: '2025-03-09T10:00:00Z',
  },
  {
    id: 'act3',
    userId: '2',
    type: 'resource',
    action: 'Downloaded resource',
    details: 'Understanding Anxiety: A Faith-Based Approach',
    timestamp: '2025-03-11T09:15:00Z',
  },
]

export const MOCK_USER_SESSIONS: UserSession[] = [
  {
    id: 'sess1',
    userId: '1',
    therapistId: 'th1',
    therapistName: 'Dr. Sarah Johnson',
    date: '2025-03-09T10:00:00Z',
    duration: 50,
    status: 'completed',
    rating: 5,
    feedback: 'Very helpful session',
  },
  {
    id: 'sess2',
    userId: '1',
    therapistId: 'th1',
    therapistName: 'Dr. Sarah Johnson',
    date: '2025-03-02T10:00:00Z',
    duration: 50,
    status: 'completed',
    rating: 4,
  },
  {
    id: 'sess3',
    userId: '2',
    therapistId: 'th2',
    therapistName: 'Dr. Michael Brown',
    date: '2025-03-10T14:00:00Z',
    duration: 50,
    status: 'scheduled',
  },
]

export const MOCK_USER_RESOURCES: UserResource[] = [
  {
    id: 'ur1',
    userId: '1',
    resourceId: 'res1',
    resourceTitle: 'Understanding Anxiety',
    resourceType: 'book',
    accessedAt: '2025-03-01T11:20:00Z',
    completed: true,
    bookmarked: true,
    rating: 5,
  },
  {
    id: 'ur2',
    userId: '1',
    resourceId: 'res2',
    resourceTitle: 'Daily Devotionals',
    resourceType: 'book',
    accessedAt: '2025-03-05T09:30:00Z',
    bookmarked: true,
  },
]